name: Scheduled README Update

on:
  schedule:
    - cron: '0 */3 * * *' # a cada 3 horas
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Criar um commit vazio para forçar refresh
        run: |
          git config user.email "artemiz.onion@gmail.com"
          git config user.name "Artemiz"
          git commit --allow-empty -m "ci(update): forcing README refresh" || echo "Nenhuma alteração para commitar"

      - name: Fazer push para o repositório
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
