name: Scheduled README Update

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: checkout do repositório
        uses: actions/checkout@v4

      - name: criar um commit vazio para forçar refresh
        run: |
          git config --global user.email "artemiz.onion@gmail.com"
          git config --global user.name "Artemiz"
          git commit --allow-empty -m "ci(update): forcing README refresh"
      
      - name: fazer push para o repositório
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
